Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Role")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly DataContext _dataContext;
        public RoleController(DataContext context)
        {
            _dataContext = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _dataContext.Roles.OrderByDescending(r => r.Id).ToListAsync());
        }

		// Hiển thị form tạo mới thương hiệu
		[HttpGet]
		[Route("Create")]  // Route sẽ là Admin/Role/Create
		public async Task<IActionResult> Create()
		{
			return View();
		}
	}
}

Shopping_Tutortial/Shopping_Tutortial/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Models;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Controllers
{
	
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;

		public BrandController(DataContext context)
		{
			_dataContext = context;
		}

		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _dataContext.Brands.Where(c => c.Slug == Slug).FirstOrDefault();

			if (brand == null) return RedirectToAction("Index");

			var productsByBrand = _dataContext.Products.Where(p => p.BrandId == brand.Id);

			return View(await productsByBrand.OrderByDescending(p => p.Id).ToListAsync());
		}

	}
}

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Role/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityRole>
@{
    ViewData["title"] = "Brand list";
    // Paginate pager = new Paginate();
    // int pageNo = 0;
    // if (ViewBag.Pager != null)  // Thay đổi kiểm tra ViewBag.Pager
    // {
    //     pager = ViewBag.Pager;
    //     pageNo = pager.CurrentPage;
    // }
}
<h1>List Role</h1>
<a class="btn btn-primary" asp-action="Create" asp-controller="Role">Add Role</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Role Name</th>
            <th scope="col">Role </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
            
                

                <td>
                    <a asp-action="Edit" class="btn btn-warning btn-sm" asp-controller="Brand" asp-route-Id="@item.Id">Edit</a>
                    <a asp-action="Delete" class="btn btn-danger btn-sm confirmDeletion" asp-controller="Brand" asp-route-Id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>
@* <partial name="_paging" model="@pager" /> *@