Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class OrderController : Controller
	{
		private readonly DataContext _dataContext;

		public OrderController(DataContext context)
		{
			_dataContext = context;
		}
		public async Task<IActionResult> Index()
		{
			return View(await _dataContext.Orders.OrderByDescending(o => o.Id).ToListAsync());
		}

		public async Task<IActionResult> ViewOrder(string ordecode)
		{
			var DetailsOrder = await _dataContext.OrderDetails.Include(od=>od.Product).Where(od=>od.OrderCode == ordecode).ToListAsync();
			return View(DetailsOrder);
		}
	}
}

Shopping_Tutortial/Shopping_Tutortial/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Models;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Controllers
{
	public class CategoryController : Controller
	{
		private readonly DataContext _dataContext;
		public CategoryController(DataContext context)
		{
			_dataContext = context;
		}
		public async Task<IActionResult> Index(string Slug = "")
		{
			CategoryModel category = _dataContext.Categories.Where(c => c.Slug == Slug).FirstOrDefault();

			if(category == null) return RedirectToAction("Index");

			var productsByCategory = _dataContext.Products.Where(p => p.CategoryId == category.Id);

			return View(await productsByCategory.OrderByDescending(p =>p.Id).ToListAsync());
		}
	}
}

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Order/Index.cshtml
@model IEnumerable<OrderModel>
@{
    ViewData["title"] = "Danh Sách Đơn Hàng";
}
<h1>List Order</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Order Code</th>
            <th scope="col">Order UserName</th>
			<th scope="col">Order Data</th>
            <th scope="col">Order Status</th> 
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>#</th>
                <th scope="row">@item.OrderCode</th>
                <td>@item.UserName</td>
                <td>@item.CreatedDate</td>
                <td>
                    @if (item.Status == 1)
                    {
                        <span class=" text text-success">Đơn hàng mới</span>
                    }
                    else
                    {
                        <span class="text text-danger">Đơn hàng thành công</span>
                    }
                </td>

                <td>
                    <a asp-action="ViewOrder" class="btn btn-warning btn-sm" asp-controller="Category" asp-route-ordercode="@item.OrderCode">View Order</a>
                    <a asp-action="Delete" class="btn btn-danger btn-sm confirmDeletion" asp-controller="Order" asp-route-Id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Order/ViewOrder.cshtml
@model IEnumerable<OrderDetails>
@{
    ViewData["title"] = "Chi tiết Đơn Hàng";
}
<h1>List Order</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Order Code</th>
            <th scope="col">Order UserName</th>
            <th scope="col">Order Data</th>
            <th scope="col">Order Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>#</th>
                <th scope="row">@item.OrderCode</th>
               @*  <td>@item.UserName</td>
                <td>@item.CreatedDate</td>
                <td>
                    @if (item.Status == 1)
                    {
                        <span class=" text text-success">Đơn hàng mới</span>
                    }
                    else
                    {
                        <span class="text text-danger">Đơn hàng thành công</span>
                    }
                </td> *@

               
            </tr>
        }

    </tbody>
</table>