Shopping_Tutortial/Shopping_Tutortial/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Models;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Controllers
{
	
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;

		public BrandController(DataContext context)
		{
			_dataContext = context;
		}

		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _dataContext.Brands.Where(c => c.Slug == Slug).FirstOrDefault();

			if (brand == null) return RedirectToAction("Index");

			var productsByBrand = _dataContext.Products.Where(p => p.BrandId == brand.Id);

			return View(await productsByBrand.OrderByDescending(p => p.Id).ToListAsync());
		}

	}
}

Shopping_Tutortial/Shopping_Tutortial/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutortial.Models;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Controllers
{
	public class CategoryController : Controller
	{
		private readonly DataContext _dataContext;
		public CategoryController(DataContext context)
		{
			_dataContext = context;
		}
		public async Task<IActionResult> Index(string Slug = "")
		{
			CategoryModel category = _dataContext.Categories.Where(c => c.Slug == Slug).FirstOrDefault();

			if(category == null) return RedirectToAction("Index");

			var productsByCategory = _dataContext.Products.Where(p => p.CategoryId == category.Id);

			return View(await productsByCategory.OrderByDescending(p =>p.Id).ToListAsync());
		}
	}
}

Shopping_Tutortial/Shopping_Tutortial/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Shopping_Tutortial.Repository;

namespace Shopping_Tutortial.Controllers
{
	public class ProductController : Controller
	{
		private readonly DataContext _dataContext;
		public ProductController(DataContext context)
		{
			_dataContext = context;
		}
		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Detail(int Id )
		{
			if(Id == null) return RedirectToAction("Index");
			var productsById = _dataContext.Products.Where(p => p.Id == Id).FirstOrDefault();
			return View(productsById);
		}
	}
}

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title> @ViewData["title"] - Admin Areas | E-Shopper</title>
	<link href="~/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/css/font-awesome.min.css" rel="stylesheet">
	<link href="~/css/prettyPhoto.css" rel="stylesheet">
	<link href="~/css/price-range.css" rel="stylesheet">
	<link href="~/css/animate.css" rel="stylesheet">
	<link href="~/css/main.css" rel="stylesheet">
	<link href="~/css/responsive.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	<link rel="shortcut icon" href="images/ico/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	
	<header id="header">
		<!--header-->
		<div class="header_top">
			<!--header_top-->
			<div class="container">
				<div class="row">
					
					
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle">
			<!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="images/home/logo.png" alt="" /></a>
						</div>
						<div class="btn-group pull-right">
							

							
						</div>
					</div>
					
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom">
			<!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a asp-action="Index" asp-controller="Home" class="active">Home</a></li>
								
								<li><a asp-controller="Product" asp-action="Index">Manage Products</a></li>
								<li><a asp-controller="Category" asp-action="Index">Manage Category</a></li>
								<li><a asp-controller="Brand" asp-action="Index">Manage Brands</a></li>
								<li><a asp-controller="Order" asp-action="Index">Orders</a></li>
								<li><a asp-controller="User" asp-action="Index">Manage User</a></li>
								<li><a asp-controller="Role" asp-action="Index">Manage Roles</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search" />
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

	

	<section>
		<div class="container">
			<div class="row">
				@Html.Partial("_NotificationPartial")
				@RenderBody()
			</div>
		</div>
	</section>


	<footer id="footer"><!--Footer-->

	</footer><!--/Footer-->


	<script src="~/js/jquery.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/jquery.scrollUp.min.js"></script>
	<script src="~/js/price-range.js"></script>
	<script src="~/js/jquery.prettyPhoto.js"></script>
	<script src="~/js/main.js"></script>
	<script src="~/backend/js/site.js"></script>
	@await RenderSectionAsync("Scripts",required:false)
</body>
</html>

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if(TempData["success"]!=null)
{
	<div class="alert alert-success notification">
		@TempData["success"]
	</div>
}

@if(TempData["error"]!=null)
{
	<div class="alert alert-success notification">
		@TempData["error"]
	</div>
}

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Shared/_Paging.cshtml
@model Shopping_Tutortial.Models.Paginate
<div class="container">
    @if (Model.TotalPages > 0) //2 trang
    {
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }
            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++) //1 = 1 <= 2
            {
                <li class="page-item @(pge==Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

Shopping_Tutortial/Shopping_Tutortial/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="left-sidebar">
	<h2>Category</h2>
	<div class="panel-group category-products" id="accordian">
		<!--category-productsr-->
		<vc:Categories></vc:Categories>
		
	</div><!--/category-products-->
	<h2>Brands</h2>
	<div class="panel-group category-products" id="accordian">
		<!--brands_products-->
		
		<vc:brands></vc:brands>
	</div><!--/brands_products-->


	
</div>